export default Object.freeze({
    FETCH_USERS:             'FETCH_USERS',
    FETCH_USERS_SUCCESS:     'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAIL:     	 'FETCH_USERS_FAIL',
    FETCH_USER_DATA:         'FETCH_USER_DATA',
    FETCH_USER_DATA_SUCCESS: 'FETCH_USER_DATA_SUCCESS',
    FETCH_USER_DATA_FAIL:    'FETCH_USER_DATA_FAIL',
    CLEAR_USER_DATA: 		 'CLEAR_USER_DATA',
    START_FETCHING: 		 'START_FETCHING',
    STOP_FETCHING:  		 'STOP_FETCHING',
    SET_POP_UP_TOP:          'SET_POP_UP_TOP',
    SET_META_DATA:           'SET_META_DATA'
});
